### ISSUE TITLE
Replace pwb with pwd

### ISSUE THREAD

**Issue by MaxGhenis** [UBICenter/us-calc#16]
I assume this is for people with disabilities?

**Comment by ngpsu22** [comment]
Whoops yeah, I'll fix that

**Comment by MaxGhenis** [comment]
Still here, could you tag this issue in the PR that closes it?

https://github.com/UBICenter/us-calc/blob/64dbe5fa073eafbaba3afb685fed1f519437fee8/funding.py#L37-L40
