### ISSUE TITLE
Update Compute Studio app

### ISSUE THREAD

**Issue by MaxGhenis** [UBICenter/us-calc#70]
@hdoupe could you please update this app on CS? We've made a few changes and we're presenting it at a conference on Saturday.

**Comment by hdoupe** [comment]
Absolutely, I'll push it now

**Comment by hdoupe** [comment]
Are you planning to embed this on the UBI center website or link directly to it on C/S?

(I'm asking because I just added support for dynamically re-sizing data visualizations when embedded as iframes. This will help it scale appropriately for all device sizes.)

**Comment by MaxGhenis** [comment]
For now we're just redirecting http://uscalc.ubicenter.org but yeah I think we should be able to get embedding working by Saturday, wdyt @fedderw?

**Comment by hdoupe** [comment]
@MaxGhenis it looks like there was an issue building the environment. I don't know if `us` is on conda-forge? https://github.com/UBICenter/us-calc/blob/main/environment.yml#L6

**Comment by MaxGhenis** [comment]
`us` is on conda-forge: https://anaconda.org/conda-forge/us

But I just changed the environment file to install it from pip instead

**Comment by hdoupe** [comment]
Ah, thanks @MaxGhenis . Trying again

**Comment by fedderw** [comment]
> For now we're just redirecting http://uscalc.ubicenter.org but yeah I think we should be able to get embedding working by Saturday, wdyt @fedderw?

Sounds good to me

**Comment by hdoupe** [comment]
Hmmm, getting this `us` not installed error: https://github.com/compute-tooling/compute-studio-publish/runs/2852112587#step:9:61

**Comment by hdoupe** [comment]
@MaxGhenis @fedderw the embed docs are here: https://docs.compute.studio/publish/data-viz/embed.html

Disclaimer: I just added them. Please let me know if you notice any issues

**Comment by hdoupe** [comment]
Update is live: https://github.com/compute-tooling/compute-studio/projects/1

Please let me know if there's anything else that I can do to help out!

**Comment by MaxGhenis** [comment]
@hdoupe could you update it again? We just put out a new release. Hoping to announce on the blog tomorrow (Wednesday) if possible.

**Comment by MaxGhenis** [comment]
Thanks @hdoupe for the quick turnaround!
